---
- name: Probe restic repository
  ansible.builtin.command:
    argv:
      - /usr/local/bin/restic
      - --insecure-no-password
      - --no-cache
      - cat
      - config
  environment: "{{ restic_backup_environment }}"
  become: true
  become_user: "{{ web_user }}"
  register: _restic_backup_repository_probe
  changed_when: false
  failed_when: _restic_backup_repository_probe.rc not in [0, 10]

- name: Initialize restic repository
  when: _restic_backup_repository_probe.rc == 10
  ansible.builtin.command:
    argv:
      - /usr/local/bin/restic
      - --insecure-no-password
      - --option
      - s3.storage-class=INTELLIGENT_TIERING
      - init
  environment: "{{ restic_backup_environment }}"
  become: true
  become_user: "{{ web_user }}"
  changed_when: true
